project:
  type: website

website:
  title: "Maxim Wenninger"
  search: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: notes.qmd
        text: Notes
      - href: about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/maximwenninger
        aria-label: GitHub

  page-footer:
    center: "© 2026 Maxim Wenninger"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true